name: vi_text_input_formatter
description: Simple Flutter package for direct Vietnamese text inputting
version: 1.0.0
repository: https://github.com/VinhPhmCng/vi_text_input_formatter
issue_tracker: https://github.com/VinhPhmCng/vi_text_input_formatter/issues
topics:
  - utils

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
